---
- name: Prepare AI Asistant Variables
  ansible.builtin.include_tasks: prepare_variables.yaml

- name: Deploy Showroom AI Assistant (single instance)
  vars:
    _showroom_namespace: "{{ ocp4_workload_showroom_ai_assistant_namespace }}"
    _showroom_vars: >-
      {{
        _showroom_global_data
        | combine(
            _showroom_user_data.users.user1 | default({}),
            {'guid': guid},
            recursive=True
          )
      }}
  ansible.builtin.include_tasks: deploy_showroom_ai_assistant.yaml

